version: '3.8'

services:
  mysql:
    image: mysql:9.0.1
    container_name: mysql_db
    environment:

      # In a real world, we would store these passwords in something like SecretsManager, but since this is a test app,
      # it's OK to hardcode them
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: link_squeeze
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_service
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      # In a real world, we would store these passwords in something like SecretsManager, but since this is a test app,
      # it's OK to hardcode them
      SPRING_DATASOURCE_URL: jdbc:mariadb://mysql_db:3306/link_squeeze?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app-network

  angular-app:
    build:
      context: ./link-squeeze-website  # Update this path to your Angular project directory
      dockerfile: Dockerfile  # Assuming the Angular Dockerfile is named `Dockerfile`
    container_name: angular-app
    depends_on:
      - api
    ports:
      - "4200:4200"  # Map container's port 4200 to host's port 4200
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
